### ISSUE TITLE
消息通知的字体

### ISSUE THREAD

**Issue by LjieQ** [kongzue/Dialog#12]
希望能提供修改消息通知高度、字体大小和颜色的方法。ps：这个库真的很好用

**Comment by kongzue** [comment]
嗯，这个我会考虑做的，预期两个版本内更新

**Comment by kongzue** [comment]
已在 2.3.1 版本中：新增 DialogSettings.notification_text_color 控制 Notification 标题和消息默认颜色，以及
新增 DialogSettings.notification_text_size 控制 Notification 标题和消息默认字号，详情请参考更新日志。
