### ISSUE TITLE
偶尔弹窗样式是Material风格，弹窗会显示不全

### ISSUE THREAD

**Issue by lemonL** [kongzue/Dialog#13]
明明初始化的时候设置了Kongze样式，偶尔会显示默认的Material风格弹窗，有时候，弹窗还显示不全，下面的取消按钮那一栏都消失了，再重新弹出弹窗就好了。
有的时候 重启APP 就恢复了。

**Comment by kongzue** [comment]
使用Material风格时实际上就是调用的标准 android.support.v7.app.AlertDialog ，如果出现问题，可能是厂商修改系统组件导致的，可以的话请告诉我您的测试系统和机型，我会做一下排查

**Comment by lemonL** [comment]
@kongzue  没有使用Material 风格。。。。是初始化Dialog的时候选择其他风格，偶尔会变成Material，感觉像是初始化失败一样，其次就是弹窗显示不全。。。。我这边再复现的话，会截图给你看一下

**Comment by lemonL** [comment]
![device-2018-09-17-150109](https://user-images.githubusercontent.com/5005866/45611031-a4ef4000-ba90-11e8-9e52-ff767d144cab.png)
![device-2018-09-17-150306](https://user-images.githubusercontent.com/5005866/45611035-a91b5d80-ba90-11e8-94a3-4a9e3266f5db.png)
![_20180917150215](https://user-images.githubusercontent.com/5005866/45611036-a9b3f400-ba90-11e8-8610-cb03130fb3ab.png)
![_20180917150225](https://user-images.githubusercontent.com/5005866/45611037-aa4c8a80-ba90-11e8-97b8-9a969c0c4697.png)
![_20180917150322](https://user-images.githubusercontent.com/5005866/45611041-ad477b00-ba90-11e8-8cce-b368c78d8422.png)

提示框显示不全又复现了。。
@kongzue

**Comment by kongzue** [comment]
您好，在 Kongzue 的 Dialog 文档中有[说明](https://github.com/kongzue/Dialog#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%B8%83%E5%B1%80)，从 2.2.3 版本起支持 MessageDialog、SelectDialog、InputDialog和BottomMenu 的自定义布局，因为一些原因，选择 Material 风格时仅支持对话框全部使用自定义布局。

稍后我会对 Material 风格的自定义布局进行一些修改，尽量解决这个问题

**Comment by kongzue** [comment]
您好，已更新2.3.3版本，请更新最新版本后参阅文章章节[《自定义布局》](https://github.com/kongzue/Dialog#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%B8%83%E5%B1%80) 的说明

**Comment by lemonL** [comment]
@kongzue 
![_20180917172917](https://user-images.githubusercontent.com/5005866/45615618-a2e0ad80-ba9f-11e8-9888-0f659966312a.png)


是参考着来的。。应该没什么问题吧。。
版本是2.3.0
需要更新到2.3.3吗？

**Comment by kongzue** [comment]
请更新至2.3.3版本，并参照[《自定义布局》](https://github.com/kongzue/Dialog#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%B8%83%E5%B1%80)中的说明进行编写，对于 Material 风格的自定义布局 Dialog 请先使用 build(...) 方法进行创建，其后使用setCustomView(...) 设置您的自定义布局，最后使用 showDialog(); 方法启动它。
因为执行顺序不同，Material 风格与其他风格在使用自定义布局时写法是不同的，请严格按照文档提示进行。
