### ISSUE TITLE
SelectDialog 不能设置取消文字的颜色吗

### ISSUE THREAD

**Issue by m511386374** [kongzue/Dialog#16]

**Comment by kongzue** [comment]
会在之后的版本考虑加入此设置项

**Comment by m511386374** [comment]
什么时候将在出新版本呀

**Comment by kongzue** [comment]
预计两天内，最近比较忙还请谅解

**Comment by m511386374** [comment]
恩恩好的

**Comment by kongzue** [comment]
目前如果您使用ios风格的话，直接设置DialogSettings.ios_normal_button_color就可以改变按钮文字颜色（含取消按钮文字颜色），若想单独改变确定按钮文字颜色，可以通过修改DialogSettings.ios_normal_ok_button_color实现

**Comment by kongzue** [comment]
若是用别的风格，material风格的按钮文字颜色取决于您的项目res/value/color.xml中的colorPrimary配置的颜色，Kongzue风格暂时不支持自定义按钮颜色

**Comment by m511386374** [comment]
好的谢谢

**Comment by kongzue** [comment]
您好，新版本已修改文字样式设置方式，几乎支持所有文字进行样式修改，请查看更新日志了解更多
