### ISSUE TITLE
消息通知可以去掉阴影吗

### ISSUE THREAD

**Issue by xvalerian** [kongzue/Dialog#17]
这个阴影对沉浸式状态栏不友好,最好可以选择从上还是从下弹出

**Comment by kongzue** [comment]
您好，Notifaction因为需要跨Activity实现，而又无需悬浮窗权限，本质上是通过修改Toast实现的，但目前我们在最新版本的Android系统上进行测试，Toast已经无法实现任何出入场动画效果了，如果您有办法可以告诉我，感激不尽

**Comment by xvalerian** [comment]
我刚刚试了一下,高版本Android系统toast确实无法修改Toast动画，去阴影我已经自己通过修改xml实现。感谢回复
