### ISSUE TITLE
需要新的功能？

### ISSUE THREAD

**Issue by kongzue** [kongzue/Dialog#2]
我知道基础业务逻辑的简单消息对话框、输入框、选择框已经不能满足你啦。
还需要什么框？说说看！

**Comment by xsjqqq123** [comment]
Notification是否能自定义位置，上中下。BottomMenu添加个最上方的标题。输入对话框确认时，可以阻止关闭。

**Comment by kongzue** [comment]
输入对话框可以使用setCanCancel方法设置是否可以关闭。BottomMenu的标题在路上了，Notification从其他位置出来...有些违和啊

**Comment by xsjqqq123** [comment]
bottom menu的字体目前写死了，最好能修改。

**Comment by kongzue** [comment]
@xsjqqq123 需要怎样修改？

**Comment by xsjqqq123** [comment]
能定义大小，默认的字体大小对于我们APP来说，看起来过大了。也许可以用DialogSettings.dialog_button_text_size 的值，或者类似

**Comment by xsjqqq123** [comment]
这个bottom menu还没完善？看了下源码，中文直接写到layout里边了 。。

**Comment by kongzue** [comment]
@xsjqqq123 嗯，这个我会在下个版本更新。另外就是BottomMenu确实是后加入的，在一些功能上还不完善，这个也会尽快完善的。预计更新时间为三天内，敬请期待！

**Comment by Gitgitgitgghub** [comment]
大神您好，小弟從2.1X版本開始使用，記得那時候inputDialog 點選確定或取消後 輸入框會自行關閉，現在一定得用戶點選取消才可以關閉，好像有點奇怪，是否遺漏了呢?

**Comment by kongzue** [comment]
@Gitgitgitgghub 最新版本在InputDialog使用时确定按钮已经不再直接响应dismiss而需要手动dismiss，另外，你也可以通过监控Dialog的生命周期进行操作。

**Comment by a707897664** [comment]
能够添加 全局设置提示框设置是否可以点击对话框以外的区域关闭对话框

**Comment by kongzue** [comment]
@a707897664 .setCanCancel(boolean)可以设定

**Comment by wlingf** [comment]
自定义view 怎么让view里的控件点击事件让dialog消失

**Comment by kongzue** [comment]
@wlingf 目前你可以直接DialogSettings.unloadAllDialog();这个我会想办法提供方法的

**Comment by wlingf** [comment]
希望快点提供相应的方法

**Comment by a707897664** [comment]
@kongzue 那个不是全局设置的  如果dialog有很多的话每一个都要写一次setCanCancel

**Comment by xsjqqq123** [comment]
请教一下：在弹出对话框的过程中，背景过于透明，在对话框到达位置后，blur才起效，是否有解决办法？ 小米5上这个过程不明显，表现还行，但荣耀V10上就很明显了。

**Comment by xsjqqq123** [comment]
另外我们APP的bugly追踪到如下bug，不知道现在版本是否解决？
#1304 java.lang.IllegalArgumentException
width and height must be > 0

com.kongzue.dialog.util.BlurView.drawBlurredBitmap(BlurView.java:354)

**Comment by kongzue** [comment]
@a707897664 收到

**Comment by kongzue** [comment]
@xsjqqq123 目前模糊效果是调用 RenderScript 来实现的，这是目前最大程度上不会出现性能损失同时能够实现即时模糊效果的方法，他可能与 AlphaAnimation 存在冲突，但在我这边测试的大部分机器上都表现出色，此问题还有可能是由于华为对系统所作的修改导致的，具体原因有待排查

**Comment by a707897664** [comment]
自定义dialog能不能实现有两个输入框的？

**Comment by kongzue** [comment]
@nxnyk 抱歉，暂时不会支持，Kongzue Dialog这个项目的主旨在于快速创建指定样式的对话框，如果您有自定义化的需求可以使用设置自定义布局的方式，对话框大小会根据内容大小进行扩展。

**Comment by nxnyk** [comment]
WaitDialog后期会支持自定义布局吗？比如自己采用自己的动画等

**Comment by kongzue** [comment]
@nxnyk 会的，两个版本（除修复bug的版本）内

**Comment by kongzue** [comment]
@nxnyk 已在最新版本支持WaitDialog自定义布局，请查看更新日志

**Comment by kongzue** [comment]
@nxnyk 更新后默认情况下，在show(...)方法后使用setCanCancel(boolean) 则为单独设置本次是否可取消，如果在show(...)方法前使用setCanCancelGlobal(boolean) 方法则可设置全局是否可取消。

你可以先试用2.4.6.1内测版本，或者等待后续正式版本更新。

**Comment by nxnyk** [comment]
作者对于自定义布局的WaitDialog，能否全局配置，不需要每次都去获取view，又或者作者能否放开权限，我在项目中尝试继承您的Waitdialog来进行定制发现是私有的，没办法继承。

**Comment by m511386374** [comment]
而且WaitDialog.show(context, "载入中...", customView); 这个“载入中...”改成“ ”空字符串。WaitDialog不显示。
