### ISSUE TITLE
设置背景图，这个要怎么实现呢？

### ISSUE THREAD

**Issue by china-coder** [kongzue/Dialog#24]
![image](https://user-images.githubusercontent.com/13534737/48696210-39eef080-ec1c-11e8-8515-09d746277a50.png)
要实现这个效果要怎么实现呢？

**Comment by kongzue** [comment]
Dialog组件旨在提供最简单的对话框启动方式，对于特殊需求，我建议您使用自定义对话框自行开发。

**Comment by kongzue** [comment]
好吧，我考虑考虑能不能提供一个快速创建自定义布局的组件

**Comment by china-coder** [comment]
好的 我这边先用自定义对话框开发 谢谢您

**Comment by kongzue** [comment]
已经在尝试做了，预计下一版更新

**Comment by china-coder** [comment]
好的 有什么需要我这边帮忙的  我也可以加入维护项目

**Comment by kongzue** [comment]
预计一天内更新
![h _ yxi25lt zvx rkt](https://user-images.githubusercontent.com/10115359/48698607-7aea0380-ec22-11e8-85cf-5ac846b63611.jpg)

**Comment by kongzue** [comment]
请更新至 2.3.9 版本，并参照：https://github.com/kongzue/Dialog#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%AF%B9%E8%AF%9D%E6%A1%86
