### ISSUE TITLE
菜单列表报错

### ISSUE THREAD

**Issue by xiaoduv587** [kongzue/Dialog#25]
我用的2.3.9，点击菜单列表报以下错误。使用的Demo是从您git上下载的，然后使用implementation 'com.kongzue.dialog:dialog:2.3.9'报错。
本地代码没有错误，远程库有问题、
```
 java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/design/widget/BottomSheetDialog;
        at com.kongzue.dialog.v2.BottomMenu.show(BottomMenu.java:90)
```

**Comment by kongzue** [comment]
您的其他引用库可能包含'com.android.support:design'的其他版本，请使用
implementation 'com.android.support:design:27.1.0'

**Comment by xiaoduv587** [comment]
好的，谢谢您，好使了
