### ISSUE TITLE
选择对话框，底部按钮高度异常

### ISSUE THREAD

**Issue by zhangchaoxu** [kongzue/Dialog#28]
在选择对话框中，当确认和取消文字较大的时候，会和父容器的高度冲突，建议父容器高度wrap_content，然后设定确认和取消按钮的paddingVertical，这样显示效果会好一点

**Comment by kongzue** [comment]
您好，正常情况下使用，大至34dp都是没有问题的，为了保证相应风格能够正确还原和显示，暂时不提供基于wrap_content的按钮呈现方式，请问您的理想文字大小是多大？我会考虑对此修改
![snipaste_2018-11-28_11-13-13](https://user-images.githubusercontent.com/10115359/49126487-b8bfe980-f2fe-11e8-8590-9568dabc7665.png)

**Comment by zhangchaoxu** [comment]
感谢回复，我用在几个尺寸很奇葩的设备上，所以显示样式都比较大，字体用了30sp，然后显示上没什么问题，只是和按钮本身高度比较接近，所以效果没有那么好。

**Comment by kongzue** [comment]
一般情况下我更推荐直接使用dp作为文字字体单位，这是确保在任何设备上等比例显示。另外如果可以可否给我下您的异常情况下的界面截图，我会考虑此场景进行适配
