### ISSUE TITLE
需要新的功能

### ISSUE THREAD

**Issue by chenyannan** [kongzue/Dialog#3]
首先先赞下作者.作品真的很棒.另有个需求不知作者能否抽时间实现.
描述:比如收藏时候需要一个loading然后动画过渡到收藏成功动画.如果网速很快的话可能loading动作一闪而过,最好能设置延迟时间.
产品:当点击收藏时,转圈并提示加载中,延迟1秒后出现对号文字描述改为收藏成功,然后关闭对话框.如果是失败则是失败状态..这期间始终用的是一个背景方框.
现在做法:用作者的wating对话框去loading,成功后消失 再用完成提示对话框;缺点是网络好loading瞬间结束,弹出完成提示..有种是bug的味道
希望作者能实现这个功能咯十分感谢.

**Comment by kongzue** [comment]
此功能已完成，目前处理方式也不太复杂，就是将WaitDialog的dismiss延迟了500毫秒，以直接过渡到完成状态提示框，如果还有疑问可以继续提问，感谢你的建议。
