### ISSUE TITLE
对话框消息文本字体太小了

### ISSUE THREAD

**Issue by 880634** [kongzue/Dialog#30]
消息对话框比较好看，如果没有标题的情况下，只有消息文本的情况下，和按钮的文本比较后显得比较小，我个人建议是把消息文本的字体默认调大一点点

**Comment by kongzue** [comment]
您可以使用TextInfo对组件字号、字样、颜色等进行自定义。
具体请参考：https://github.com/kongzue/Dialog#%E9%99%84%E5%8A%A0%E5%8A%9F%E8%83%BD
