### ISSUE TITLE
在使用CustomDialog的时候自定义View无法唤起输入框

### ISSUE THREAD

**Issue by china-coder** [kongzue/Dialog#33]
在使用CustomDialog的时候自定义View无法获取焦点，换成alertdialog就可以

**Comment by kongzue** [comment]
![CA](https://user-images.githubusercontent.com/10115359/49856568-1f7af200-fe2b-11e8-9842-47da743c8a1d.png)
CustomDialog里使用的就是alertdialog

**Comment by kongzue** [comment]
请尝试最新版本

**Comment by china-coder** [comment]
好的
