### ISSUE TITLE
一个小问题

### ISSUE THREAD

**Issue by tengya** [kongzue/Dialog#34]
我在BaseActivity的onDestory里执行了DialogSettings.unloadAllDialog();，A需要启动B，同时A执行finish，B需要直接弹出一个提示框，根据生命周期，A的onDestory会在B的onResume之后运行，导致的后果是B的dialog一闪就没了，找了半天原因才发现，不是bug，只是反馈一下。现在改为在onPause里直接执行DialogSettings.unloadAllDialog();

**Comment by kongzue** [comment]
您好，我正在抓紧解决此问题。以往的做法，为避免WindowLeaked问题所以提供了unloadAllDialog()方法。
但现在我准备废弃它，新版本的KongzueDialog均会在可以完全避免WindowLeaked问题的情况下运行且不需要执行unloadAllDialog()，但这还需要时间进行测试和调试，如果你希望帮助测试，或体验内测版本，可以加群271127803帮助我测试（这不是我的群，但是是我和一群开发小伙伴组件的学习讨论群），也可以等待接下来的版本。
如果您在下一版更新日志中见到有我提到无需使用unloadAllDialog()方法了即代表我已经成功做到，若没有...好吧我希望能够做到。

**Comment by kongzue** [comment]
请更新尝试 2.4.2 版本，并删除 onDestroy() 中执行的 DialogSettings.unloadAllDialog()

**Comment by tengya** [comment]
感谢回复
