### ISSUE TITLE
如何动态改变dialog的文字内容

### ISSUE THREAD

**Issue by protectedMan** [kongzue/Dialog#35]

**Comment by protectedMan** [comment]
![qq20181215-160336-hd](https://user-images.githubusercontent.com/17565737/50040669-11bfa980-0083-11e9-99f0-3a09490f4578.gif)
具体需求如图，dialog显示期间内容是可以改变的

**Comment by kongzue** [comment]
我会考虑在新版本中加上去的，感谢反馈
