### ISSUE TITLE
希望可以暴露出底层使用的AlertDialog,便于使用者扩展

### ISSUE THREAD

**Issue by protectedMan** [kongzue/Dialog#36]
比如说我这个需求是dialog弹出时背景不变灰。 如果能拿到底层的AlertDialog那就方便操作了。
诸如此类可能会有很多奇葩需求。。
![image](https://user-images.githubusercontent.com/17565737/50069053-4ce8e680-0203-11e9-82cf-09abf1cd1d92.png)

**Comment by kongzue** [comment]
请更新至最新版本（2.4.3）
对对话框组件（不包含底部菜单、通知和Pop提示），新增 getAlertDialog() 方法以获取实例化的 alertDialog 对象以便于实现更多骚操作；
