### ISSUE TITLE
部分机型模糊速度慢，弹出dialog会有延迟，并且很卡。机型，华为P10手机android8.0

### ISSUE THREAD

**Issue by HuaZaiWuDi** [kongzue/Dialog#39]

**Comment by HuaZaiWuDi** [comment]
在华为另外一款手机上面却没有问题，测试其他厂商机型也没有出现类似问题。

**Comment by HuaZaiWuDi** [comment]
测试中，魅族手机大概率出现模糊效果不执行，背景黑色的问题，望知悉

**Comment by kongzue** [comment]
您好，模糊效果是使用 renderScript 来实现的，部分设备可能因为其处理器运算能力不够出现执行效率降低的问题，请您使用一下代码关闭模糊效果：
DialogSettings.use_blur = false;
要解决此问题需要设备官方更新系统或想办法提升 renderScript 的运算性能，这点我无能为力。
