### ISSUE TITLE
最新版本2.4.4 自定义对话框setCanCancel无效

### ISSUE THREAD

**Issue by TuDehua** [kongzue/Dialog#40]
之前用的2.3.9.1的是好的，最新版本里，CustomDialog.show(...).setCanCancel(true); 点击对话框外部无法使对话框消失

**Comment by kongzue** [comment]
请使用build创建对话框，之后执行showDialog()指令启动即可生效

**Comment by HuaZaiWuDi** [comment]
> 请使用build创建对话框，之后执行showDialog()指令启动即可生效

为什么设置  DialogSettings.dialog_cancelable_default = true;但是只有少部分dialog用到了，这个应该是所有的dialog都要跟随这个默认配置吧，
