### ISSUE TITLE
fragment中使用内存泄漏

### ISSUE THREAD

**Issue by gogolq** [kongzue/Dialog#46]
使用过程中有内存泄漏。100%复现 android.widget.Toast$TN.mNextView

**Comment by gogolq** [comment]
EXCLUDED LEAK.
* com.kongzue.dialog.util.KongzueDialogHelper has leaked:
* thread HandlerThread.!()! (named 'NetWorkSender')
* ↳ Message.!(obj)! , matching exclusion field android.os.Message#obj
* ↳ KongzueDialogHelper

* Reference Key: 5d711a56-92e2-4c9f-a8f2-d4fae697bd8c
* Device: OnePlus OnePlus ONEPLUS A5010 OnePlus5T
* Android Version: 9 API: 28 LeakCanary: 1.6.2 0ebc1fc
* Durations: watch=5021ms, gc=130ms, heap dump=2281ms, analysis=10947ms

* Details:
* Instance of android.os.HandlerThread
| static $class$componentType = null
| static $class$ifTable = java.lang.Object[2]@1870272448 (0x6f7a17c0)
| static $class$dexClassDefIndex = 154
| static $class$virtualMethodsOffset = 2
| static $class$dexCache = java.lang.DexCache@1870127432 (0x6f77e148)
| static $class$dexTypeIndex = 722
| static $class$methods = 1877376932
| static $class$sFields = 0
| static $class$accessFlags = 524289
| static $classOverhead = byte[208]@1872496449 (0x6f9c0741)
| static $class$primitiveType = 131072
| static $class$numReferenceStaticFields = 0
| static $class$superClass = java.lang.Thread
| static $class$vtable = null
| static $class$extData = null
| static $class$objectSizeAllocFastPath = 152
| static $class$classLoader = null
| static $class$classSize = 332
| static $class$referenceInstanceOffsets = -1073741824
| static $class$copiedMethodsOffset = 9
| static $class$classFlags = 0
| static $class$objectSize = 148
| static $class$clinitThreadId = 0
| static $class$status = -536870912
| static $class$iFields = 1875441328
| static $class$shadow$_monitor_ = 536870912
| static $class$name = "android.os.HandlerThread"
| static $class$numReferenceInstanceFields = 2
| static $class$shadow$_klass_ = java.lang.Class
| mHandler = null
| mLooper = android.os.Looper@315888424 (0x12d41328)
| mPriority = 0
| mTid = 28583
| blocker = null
| blockerLock = java.lang.Object@320244784 (0x13168c30)
| contextClassLoader = dalvik.system.PathClassLoader@315947232 (0x12d4f8e0)
| daemon = false
| eetop = 0
| group = java.lang.ThreadGroup@1865204744 (0x6f2cc408)
| inheritableThreadLocals = null
| inheritedAccessControlContext = java.security.AccessControlContext@320244792 (0x13168c38)
| lock = java.lang.Object@320244800 (0x13168c40)
| name = "NetWorkSender"
| nativeParkEventPointer = 0
| nativePeer = 3804636160
| parkBlocker = null
| parkState = 1
| priority = 5
| single_step = false
| stackSize = 0
| started = true
| stillborn = false
| target = null
| threadLocalRandomProbe = 0
| threadLocalRandomSecondarySeed = 0
| threadLocalRandomSeed = 0
| threadLocals = java.lang.ThreadLocal$ThreadLocalMap@320244808 (0x13168c48)
| threadQ = null
| threadStatus = 0
| tid = 1800
| uncaughtExceptionHandler = null
| shadow$_klass_ = android.os.HandlerThread
| shadow$_monitor_ = 0
* Instance of android.os.Message
| static $class$componentType = null
| static $class$ifTable = java.lang.Object[2]@1870274968 (0x6f7a2198)
| static $class$dexClassDefIndex = 3049
| static $class$virtualMethodsOffset = 13
| static $class$dexCache = java.lang.DexCache@1870127432 (0x6f77e148)
| static sPoolSync = java.lang.Object@1870127648 (0x6f77e220)
| static $class$dexTypeIndex = 869
| static sPool = android.os.Message@315888168 (0x12d41228)
| static gCheckRecycle = true
| static CREATOR = android.os.Message$1@1870274992 (0x6f7a21b0)
| static $class$methods = 1877364308
| static $class$sFields = 1875437008
| static $class$accessFlags = 524305
| static $classOverhead = byte[132]@1871104521 (0x6f86ca09)
| static $class$primitiveType = 131072
| static FLAGS_TO_CLEAR_ON_COPY_FROM = 1
| static $class$numReferenceStaticFields = 3
| static FLAG_IN_USE = 1
| static $class$superClass = java.lang.Object
| static $class$vtable = null
| static $class$extData = null
| static $class$objectSizeAllocFastPath = 64
| static $class$classLoader = null
| static $class$classSize = 289
| static $class$referenceInstanceOffsets = 63
| static MAX_POOL_SIZE = 50
| static $class$copiedMethodsOffset = 35
| static $class$classFlags = 0
| static $class$objectSize = 60
| static $class$clinitThreadId = 0
| static sPoolSize = 24
| static $class$status = -536870912
| static $class$iFields = 1875437156
| static $class$shadow$_monitor_ = 536870912
| static $class$name = "android.os.Message"
| static $class$numReferenceInstanceFields = 6
| static $class$shadow$_klass_ = java.lang.Class
| static FLAG_ASYNCHRONOUS = 2
| arg1 = 0
| arg2 = 0
| callback = null
| data = null
| flags = 0
| next = null
| obj = com.kongzue.dialog.util.KongzueDialogHelper@320189520 (0x1315b450)
| replyTo = null
| sendingUid = -1
| target = android.app.Dialog$ListenersHandler@320189688 (0x1315b4f8)
| what = 67
| when = 0
| shadow$_klass_ = android.os.Message
| shadow$_monitor_ = 0
* Instance of com.kongzue.dialog.util.KongzueDialogHelper
| static $class$componentType = null
| static $class$ifTable = java.lang.Object[12]@320129408 (0x1314c980)
| static $class$dexClassDefIndex = 6599
| static $class$virtualMethodsOffset = 1
| static $class$dexCache = java.lang.DexCache@315975200 (0x12d56620)
| static $class$dexTypeIndex = 4025
| static $class$methods = 3787232928
| static $class$sFields = 0
| static $class$accessFlags = 524289
| static $classOverhead = byte[748]@317532801 (0x12ed2a81)
| static $class$primitiveType = 131072
| static $class$numReferenceStaticFields = 0
| static $class$superClass = android.support.v4.app.DialogFragment
| static $class$vtable = null
| static $class$extData = null
| static $class$objectSizeAllocFastPath = 168
| static $class$classLoader = dalvik.system.PathClassLoader@315947232 (0x12d4f8e0)
| static $class$classSize = 872
| static $class$referenceInstanceOffsets = -1073741824
| static $class$copiedMethodsOffset = 5
| static $class$classFlags = 0
| static $class$objectSize = 168
| static $class$clinitThreadId = 28478
| static $class$status = -536870912
| static $class$iFields = 3787232888
| static $class$shadow$_monitor_ = 0
| static $class$name = null
| static $class$numReferenceInstanceFields = 2
| static $class$shadow$_klass_ = java.lang.Class
| alertDialog = android.support.v7.app.AlertDialog@320189744 (0x1315b530)
| onDismissListener = com.kongzue.dialog.v2.SelectDialog$1@320189832 (0x1315b588)
| mBackStackId = -1
| mCancelable = false
| mDialog = null
| mDismissed = true
| mShownByMe = false
| mShowsDialog = true
| mStyle = 0
| mTheme = 0
| mViewDestroyed = true
| mAdded = false
| mAnimationInfo = null
| mArguments = null
| mBackStackNesting = 0
| mCalled = true
| mChildFragmentManager = null
| mChildNonConfig = null
| mContainer = null
| mContainerId = 0
| mDeferStart = false
| mDetached = false
| mFragmentId = 0
| mFragmentManager = null
| mFromLayout = false
| mHasMenu = false
| mHidden = false
| mHiddenChanged = false
| mHost = null
| mInLayout = false
| mIndex = -1
| mInnerView = null
| mIsCreated = false
| mIsNewlyAdded = false
| mLayoutInflater = null
| mLifecycleRegistry = android.arch.lifecycle.LifecycleRegistry@320189848 (0x1315b598)
| mLoaderManager = null
| mMenuVisible = true
| mParentFragment = null
| mPerformedCreateView = false
| mPostponedAlpha = 0.0
| mRemoving = false
| mRestored = false
| mRetainInstance = false
| mRetaining = false
| mSavedFragmentState = null
| mSavedUserVisibleHint = null
| mSavedViewState = null
| mState = 0
| mTag = null
| mTarget = null
| mTargetIndex = -1
| mTargetRequestCode = 0
| mUserVisibleHint = true
| mView = null
| mViewModelStore = null
| mWho = null
| shadow$_klass_ = com.kongzue.dialog.util.KongzueDialogHelper
| shadow$_monitor_ = 0
* Excluded Refs:
| Field: android.os.Message.obj
| Field: android.os.Message.next
| Field: android.os.Message.target
| Field: android.view.Choreographer$FrameDisplayEventReceiver.mMessageQueue (always)
| Field: android.view.ViewGroup$ViewLocationHolder.mRoot
| Thread:FinalizerWatchdogDaemon (always)
| Thread:main (always)
| Thread:LeakCanary-Heap-Dump (always)
| Class:java.lang.ref.WeakReference (always)
| Class:java.lang.ref.SoftReference (always)
| Class:java.lang.ref.PhantomReference (always)
| Class:java.lang.ref.Finalizer (always)
| Class:java.lang.ref.FinalizerReference (always)

**Comment by gogolq** [comment]
麻烦看下。这个是用LeakCanary 抓到的。只要点击selectdialog的两个按钮。消失后就会爆出。不点击没事

**Comment by gogolq** [comment]
https://stackoverflow.com/questions/53185154/leakcanary-dialogfragment-leak-detection
跟这个几乎一样

**Comment by kongzue** [comment]
很抱歉目前无法根据您提供的日志修复此问题。1是因为目前暂未收到的类似报告，2是您提供的日志和stackoverflow问题目前没有解决办法。

**Comment by gogolq** [comment]
嗯。目前发现只有在Android 9.0才会有
