### ISSUE TITLE
dialog最好要不要关闭由使用者决定

### ISSUE THREAD

**Issue by LLQQHH** [kongzue/Dialog#5]
比如InputDialog用户没有输入东西，按确定肯定不能关闭dialog而是提示输入为空。应该加一个变量控制，默认是自动关闭。

**Comment by kongzue** [comment]
@LLQQHH 最新版本已经修改为输入对话框默认确定按钮事件不关闭，如需关闭可以手动加入dialog.dismiss()进行关闭，您可以更新至2.2.2版本。
