### ISSUE TITLE
能否让Cancelable设置成所有dialog的默认值？

### ISSUE THREAD

**Issue by HuaZaiWuDi** [kongzue/Dialog#51]
//决定对话框组件默认是否可点击遮罩区域关闭
    public static boolean dialog_cancelable_default = false;
这个属性好像只有部分dialog有用到，希望应用到所有Dialog.

**Comment by kongzue** [comment]
目前仅部分提示性对话框不适用。原因很简单，正常逻辑下等待对话框需要在等待完成时手动dismiss，提示对话框会自动在三秒后dismiss

**Comment by HuaZaiWuDi** [comment]
但是这个你把物理返回键也屏蔽了，如果出现异常导致弹窗无法取消的情况，用户只能杀死APP了，甚至有些用户都不知道如何杀死APP，这个时候对于APP是比崩溃还要恐怖的BUG

**Comment by kongzue** [comment]
Waitdialog和TipDialog支持setCanCancel(boolean)设置单次可否取消，也支持setCanCancelGlobal(boolean)设置全局是否允许返回关闭，详情请参考文档
