### ISSUE TITLE
AndroidX的项目不支持

### ISSUE THREAD

**Issue by AndyLeeBlue** [kongzue/Dialog#52]
java.lang.ClassNotFoundException: Didn't find class "com.google.android.material.bottomsheet.BottomSheetDialog"

引入
implementation 'com.google.android.material:material:1.0.0'
或者
implementation 'com.android.support:design:28.0.0'
正常

但是文字是左对齐，不是居中显示

**Comment by kongzue** [comment]
您是用的组件是？

**Comment by kongzue** [comment]
请尝试最新版本（2.4.8.2）此版本正在尝试迁移至 Android X
