### ISSUE TITLE
遇见一个BUG，TipDialog在息屏状态下，或者宿主Ac不在栈顶，然后返回Ac，Dialog会重新创建，不会消失

### ISSUE THREAD

**Issue by HuaZaiWuDi** [kongzue/Dialog#54]
![index](https://user-images.githubusercontent.com/26106636/52684350-f0931080-2f80-11e9-82d3-b86e9234da8e.gif)

**Comment by kongzue** [comment]
麻烦尝试下runOnUiThread，若还不行我再想办法

**Comment by HuaZaiWuDi** [comment]
![image](https://user-images.githubusercontent.com/26106636/53470535-dc7d0200-3a9c-11e9-845e-364e901d5ff9.png)
可能因为手机息屏状态下会暂停子线程的运行，导致延时没有调用，TipDialog无法被关闭。

**Comment by kongzue** [comment]
请尝试测试版本 2.4.7.1 或者等待更新下一个正式版本
