### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by 18856914956** [kongzue/Dialog#58]
**描述错误**
进度与提示框每次显示不一样，相同条件下有时有黑色的背景，有时没有

**复现方法**
重现行为的步骤:
1. 打开APP
2. 多次点击“等待对话框”
3. 见错误

**预期行为**
对你期望发生的事情的清晰而简洁的描述。

**截图**
![image](https://user-images.githubusercontent.com/32625233/54005194-7dea0f00-4193-11e9-9dd8-df4e958ca664.png)
![image](https://user-images.githubusercontent.com/32625233/54005205-893d3a80-4193-11e9-8d24-f95e03aa6c8f.png)

**系统信息(请填写以下信息) : **
- 版本[例如Android P]

**设备(请填写以下信息) : **
- 设备: [例如Pixel XL]
- 组件版本[例如1.0.0]

**其他**
在此添加有关此问题的任何其他信息。

**Comment by kongzue** [comment]
renderscript对于模糊的处理是需要时间的，请尝试关闭模糊效果：DialogSettings.use_blur = false; 或者禁止快速重复点击。
