### ISSUE TITLE
[BUG]底部弹出菜单快速多次点击后，先出现在中间然后才到底部

### ISSUE THREAD

**Issue by AndyLeeBlue** [kongzue/Dialog#60]
不知道这个问题应该是App自己控制用户行为，还是应该对话框控件提供控制，但是不控制的话，就会有这个问题存在。用提供的最新版本apk程序测试就可以看到：先双击“底部菜单”，然后正常点击“底部菜单”，几次之后就能看到这个问题了，谢谢！

**Comment by nxnyk** [comment]
你是安卓的9 吗

**Comment by AndyLeeBlue** [comment]
是的

**Comment by kongzue** [comment]
您的设备型号是？

**Comment by AndyLeeBlue** [comment]
华为10

**Comment by kongzue** [comment]
此问题已经于DialogV3库中处理解决，您可以立即尝试迁移升级至DialogV3，若不方便升级也可等待V2版本将在未来尝试修复此问题。
