### ISSUE TITLE
[BUG]同在redmi note7上遇到调用底部bottom菜单，弹出动画为 从屏幕中间向下弹出到屏幕底部

### ISSUE THREAD

**Issue by nxnyk** [kongzue/Dialog#61]
安卓版本 9.0 
复现概率 100%

**Comment by kongzue** [comment]
已知小米系统的问题，暂时无解决方案

**Comment by nxnyk** [comment]
> 已知小米系统的问题，暂时无解决方案

我下了您的源码，做了更改，发现设置的动画效果无效，一直是系统的进场动画，找了好久，还是没办法解决，只有进场动画有问题，退场有效的

**Comment by nxnyk** [comment]
> 已知小米系统的问题，暂时无解决方案

终于还是被我找到了，如下图，对window的设定不能放在show的时候，要在创建之后就设置，放在show'li'stener里面就会出现进场动画无效

![image](https://user-images.githubusercontent.com/42330422/56402383-afc0bc00-628f-11e9-9da1-aa2b53d6a4ff.png)

**Comment by kongzue** [comment]
此问题未在 pixel（Android P）上发现，我已准备入手小米9做进一步测试

**Comment by yuantang** [comment]
华为手机上也出现了这样的问题。

**Comment by kongzue** [comment]
此问题已经于DialogV3库中处理解决，您可以立即尝试迁移升级至DialogV3，若不方便升级也可等待V2版本将在未来尝试修复此问题。
