### ISSUE TITLE
[BUG]KongzueDialogHelper 引起内存泄漏

### ISSUE THREAD

**Issue by zhanlan123** [kongzue/Dialog#62]
**描述错误**
![QQ图片20190409144101](https://user-images.githubusercontent.com/7822852/55778473-8d7faf00-5ad5-11e9-9c43-ae1b4015d55d.png)
**复现方法**
重现行为的步骤:
WaitDialog.show(mContext, "登录中");
然后调用
WaitDialog.dismiss();
然后调用
TipDialog.show(mContext, “错误”, TipDialog.SHOW_TIME_SHORT, TipDialog.TYPE_WARNING);

**Comment by kongzue** [comment]
很抱歉未能复现您的问题，测试机型：pixel（Android P）、小米6（Android 8.0.0）、锤子 R1，请尝试升级至最新版本，或者提供logcat错误日志

**Comment by renjunjia3** [comment]
使用2.4.8复现了这个问题，多次SelectDialog.show()之后退出当前activity就会出现内存泄漏

**Comment by kongzue** [comment]
麻烦提供崩溃日志，我目前无法确定问题原因

**Comment by zhanlan123** [comment]
发现这个可能是系统问题。
