### ISSUE TITLE
点击dialog外边阴暗处diaolog消失

### ISSUE THREAD

**Issue by wananxin** [kongzue/Dialog#63]
**您的功能请求是否与问题相关？请描述一下。**
对问题所在的简明描述。

**描述您想要的解决方案**
对你想要的功能的清晰而简洁的描述。

**描述你考虑过的替代方案**
对您所考虑的任何替代解决方案或功能的清晰而简洁的描述。

**其他相关**
在此添加关于功能请求的任何其他上下文或截图。

**Comment by kongzue** [comment]
DialogSettings.dialog_cancelable_default = -1;              //控制消息对话框、选择对话框和输入对话框默认是否可点击外部遮罩层区域关闭，=-1不启用

**Comment by wananxin** [comment]
这个只针对了自带的dialog会有这个效果，但是自定义dailog   CustomDialog点击外部遮罩层区域关闭没这个效果

**Comment by wananxin** [comment]
哦找到了 setCanCancel

**Comment by wananxin** [comment]
部分自定义布局我想宽度是充满屏幕，但是不写死宽高布局就压缩的都是乱的 请问这个怎么解决

**Comment by kongzue** [comment]
Window window = dialog.getWindow();
WindowManager windowManager = context.getWindowManager();
Display display = windowManager.getDefaultDisplay();
WindowManager.LayoutParams lp = window.getAttributes();
lp.width = display.getWidth();
window.setAttributes(lp);
