### ISSUE TITLE
消息对话框

### ISSUE THREAD

**Issue by sumincy** [kongzue/Dialog#64]
点击回调怎么处理

**Comment by kongzue** [comment]
https://github.com/kongzue/Dialog#%E8%B0%83%E7%94%A8%E6%B6%88%E6%81%AF%E5%AF%B9%E8%AF%9D%E6%A1%86%E7%9A%84%E6%96%B9%E6%B3%95
new DialogInterface.OnClickListener() {
    ...
}

**Comment by sumincy** [comment]
谢谢
