### ISSUE TITLE
奔溃报错 Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isRecycled()' on a null object reference

### ISSUE THREAD

**Issue by Linoven** [kongzue/Dialog#66]
**描述错误**
 奔溃报错 Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isRecycled()' on a null object reference

**复现方法**
重现行为的步骤:
1. 去“……”
2. 点击“……”
3. 向下滚动到“……”
4. 见错误

**预期行为**
对你期望发生的事情的清晰而简洁的描述。

**截图**
如果适用，添加截图来帮助解释你的问题。

**系统信息(请填写以下信息) : **
- 版本[例如Android P]
android 6.0.1 API23 
**设备(请填写以下信息) : **
- 设备: [例如Pixel XL]  华为
- 组件版本[例如1.0.0]
implementation 'com.kongzue.dialog:dialog:2.4.9'
**其他**
在此添加有关此问题的任何其他信息。

**Comment by kongzue** [comment]
请关闭模糊效果 DialogSettings.use_blur = false;

**Comment by Linoven** [comment]
好的 我试试

**Comment by Linoven** [comment]
可以了， 谢谢大佬

**Comment by kongzue** [comment]
部分设备renderscript执行有问题（这个我是真没办法解决了，目前只能先关掉模糊效果凑合
