### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by lusheast** [kongzue/Dialog#67]
**描述错误**
在fragment中弹dialog的的时候，IOS风格，会出现dialog对话框的背景和其他区域背景是同一个透明度。不是每次都这样，五次里面有一次是可以正常显示的。选择对话框。

**Comment by kongzue** [comment]
初步猜测是系统问题，具体涉及dialog实现目前用的就是dialogfragment，并无其他可能导致此问题的原因

________________________________
发件人: LushEast <notifications@github.com>
发送时间: Monday, May 13, 2019 3:59:58 PM
收件人: kongzue/Dialog
抄送: Subscribed
主题: [kongzue/Dialog] [BUG] (#67)


描述错误
在fragment中弹dialog的的时候，IOS风格，会出现dialog对话框的背景和其他区域背景是同一个透明度。不是每次都这样，五次里面有一次是可以正常显示的。选择对话框。

―
