### ISSUE TITLE
[BUG]WaitDialog对话框如果提示信息为10个字，不会自动换行。

### ISSUE THREAD

**Issue by zhanlan123** [kongzue/Dialog#68]
**描述错误**
WaitDialog对话框如果提示信息为10个字，不会自动换行。

**复现方法**
重现行为的步骤:
1. WaitDialog.show(mContext, “正在获取资金转移列表”);

**预期行为**
提示信息可以自动换行

**截图**
如果适用，添加截图来帮助解释你的问题。

**系统信息(请填写以下信息) : **
- 版本[例如Android P]

**设备(请填写以下信息) : **
- 设备: [例如Pixel XL]
- 组件版本[例如1.0.0]

**其他**
在此添加有关此问题的任何其他信息。

**Comment by zhanlan123** [comment]
![image](https://user-images.githubusercontent.com/7822852/57917214-cd049c80-78c6-11e9-9b24-7e32b99b63cd.png)

**Comment by kongzue** [comment]
请更新至2.5.1版本，已修复此问题。

**Comment by zhanlan123** [comment]
谢谢，麻烦了
