### ISSUE TITLE
你这个WaitDialog.show(getContext(), "载入中...") 这个有bug呀老哥.

### ISSUE THREAD

**Issue by m511386374** [kongzue/Dialog#7]

**Comment by m511386374** [comment]
不好意思,因为我的我没有升级框架版本.升级之后就没有了

**Comment by deleteNames** [comment]
bug升级了以后依然有啊，然而我改了一些源代码，问题处在这里
public static WaitDialog show(Context context, String tip) {
        synchronized (WaitDialog.class) {
            WaitDialog waitDialog = new WaitDialog();
            waitDialog.cleanDialogLifeCycleListener();
            waitDialog.context = context;
            waitDialog.tip = tip;
            waitDialog.log("装载等待对话框 -> " + tip);
            waitDialog.waitDialog = waitDialog;
            waitDialog.showDialog();
            return waitDialog;
        }
    }
这里清空了一下DialogLifeCycleListener();导致如果我这样写的话
WaitDialog.show(context, "载入中...").setCanCancel(true).setDialogLifeCycleListener(new DialogLifeCycleListener() {
    @Override
    public void onCreate(AlertDialog alertDialog) {
        //此时对话框创建
    }
    @Override
    public void onShow(AlertDialog alertDialog) {
        //此时对话框显示
    }
    @Override
    public void onDismiss() {
        //此时对话框关闭
    }
});
那个onCreate和onShow就没走，你知道为什么吗，因为你那边判断是否为空，如果为空的情况下不走，所以我就这样改了一下
public static WaitDialog show(Context context, String tip,DialogLifeCycleListener listener) {
        synchronized (WaitDialog.class) {
            WaitDialog waitDialog = new WaitDialog();
            waitDialog.cleanDialogLifeCycleListener();
            waitDialog.context = context;
            waitDialog.tip = tip;
            waitDialog.log("装载等待对话框 -> " + tip);
            waitDialog.waitDialog = waitDialog;
            waitDialog.setDialogLifeCycleListener(listener);
            waitDialog.showDialog();

            return waitDialog;
        }
    }
就将就的用吧

**Comment by deleteNames** [comment]
你代码写的没有问题，但是没有考虑到代码运行时间的时间差的问题，导致这个问题的产生

**Comment by kongzue** [comment]
收到，将在下一版解决

**Comment by kongzue** [comment]
@deleteNames 请更新2.4.1版本进行测试
