### ISSUE TITLE
use_blur 设置为false 还会出现 半透明效果

### ISSUE THREAD

**Issue by protectedMan** [kongzue/Dialog#73]
![image](https://user-images.githubusercontent.com/17565737/63839440-e337f380-c9b1-11e9-8e65-d3a9eb41226f.png)
![image](https://user-images.githubusercontent.com/17565737/63839455-eb902e80-c9b1-11e9-9229-b1675cf58264.png)
参数和效果如图

**Comment by kongzue** [comment]
use_blur 设置为false **才会**出现 半透明效果。没问题啊

**Comment by kongzue** [comment]
开启模糊效果会调用 renderscript 渲染高斯模糊，否则会显示10%左右透明度的白色背景

**Comment by protectedMan** [comment]
好的懂了
