### ISSUE TITLE
[BUG]crash 

### ISSUE THREAD

**Issue by Justart2** [kongzue/Dialog#77]
11-20 08:45:58.185 30661 30661 E AndroidRuntime: java.lang.ClassCastException: xxxxxxx.MainActivity cannot be cast to android.support.v7.app.AppCompatActivity
11-20 08:45:58.185 30661 30661 E AndroidRuntime:        at com.kongzue.dialog.v2.SelectDialog.showDialog(SelectDialog.java:175)

dont support Activity? only .AppCompatActivity?

**Comment by kongzue** [comment]
Yes, only AppCompatActivity.
this response use SupportFragmentManager and supportFragmentManager is only in AppCompatActivity.

**Comment by Justart2** [comment]
ok , Thanks
