### ISSUE TITLE
只是在Gradle中导入依赖，就报了如下错误

### ISSUE THREAD

**Issue by zhuangYuFeiHelloGit** [kongzue/Dialog#8]
Program type already present: android.arch.lifecycle.LiveData$LifecycleBoundObserver
Message{kind=ERROR, text=Program type already present: android.arch.lifecycle.LiveData$LifecycleBoundObserver, sources=[Unknown source file], tool name=Optional.of(D8)}

能通过编译，运行失败。

**Comment by kongzue** [comment]
重复引用了相同的包导致的，这个得查具体是哪个包导致的问题

**Comment by zhuangYuFeiHelloGit** [comment]
好的谢谢
